sudo: false

language: cpp

compiler: [clang, gcc]
os: [windows, osx, linux]
dist:
  - xenial
  - bionic
osx_image:
  - xcode9.4
  - xcode10
  - xcode11
  - xcode12
  - xcode12.2

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
