language: cpp

compiler: [clang, gcc]
os: [osx, linux]
dist: focal

osx_image:
  - xcode10
  - xcode11
  - xcode12

jobs:
  include:
    - os: windows

git:
  depth: 1

script:
  - mkdir build
  - cd build
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]
      then
        cmake .. -G 'MinGW Makefiles'
      else
        cmake ..
    fi
  - cmake --build .
  - ctest -VV
